[package]
name = "DGENCoin"
version = "1.0.0"
upgrade_policy = "immutable"

[addresses]
dgen_coin = "0x2ec4190dd6eec80913e02da22de89700a9b5e13e27b51750191b7ceb3eee1a2f"

# Test addresses.
alice = "0x10"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a2a3bf79b68823287f962bded2abfaefc688e71c"
subdir = "aptos-move/framework/aptos-framework"
